name: kdev armbian build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # set_release: [ bullseye, bookworm, jammy, noble ]
        set_release: [ trixie ]
        # set_release: [ bullseye, bookworm, jammy, noble, focal, forky, oracular, plucky, resolute, trixie ]
        # bullseye	Debian 11	    Oldstable（旧稳定版）	2021年8月	安全支持将持续至 2026年6月（LTS）
        # bookworm	Debian 12	    Stable（当前稳定版）	2023年6月	当前官方推荐稳定版本
        # trixie	Debian 13	    Testing（测试版）	预计 2025 年中发布	当前处于开发冻结前阶段
        # forky	    Debian 14	    Unstable（未来开发版）	尚未发布	在 sid 之后的下一个开发代号
        # focal	    Ubuntu 20.04	LTS（长期支持）	2020年4月	标准支持已于 2025年4月结束；需 Ubuntu Pro 获取扩展安全维护（ESM）
        # jammy	    Ubuntu 22.04	LTS	2022年4月	免费支持至 2027年4月（桌面/服务器）
        # noble	    Ubuntu 24.04	LTS	2024年4月	最新 LTS，支持至 2029年4月
        # oracular	Ubuntu 24.10	普通版（非LTS）	2024年10月	支持至 2025年7月（仅9个月）
        # plucky	Ubuntu 25.04	普通版（计划）	预计 2025年4月	尚未发布，开发代号
        # resolute	Ubuntu 25.10	普通版（计划）	预计 2025年10月	未来版本，已公布代号
        set_desktop: [ cli, gnome, xfce ]
        exclude:
          - set_release: bullseye
            set_desktop: gnome
          - set_release: bullseye
            set_desktop: xfce

    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install python2 python2-dev python-is-python3 squashfs-tools rar $(curl -fsSL https://tinyurl.com/ubuntu2204-build-armbian) u-boot-tools gcc-aarch64-linux-gnu
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo timedatectl set-timezone "${TZ}"
          # init output prefix  ${{ steps.init.outputs.build_tag }}
          echo "build_tag=Armbian_ea_3588s_${{ matrix.set_release }}_5.10.226_${{ matrix.set_desktop }}" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create simulated physical disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner.runner /builder
          df -Th

      - name: Download armbian source code
        id: down_armbian
        working-directory: /builder/
        run: |
          set -x
          git clone -q --single-branch \
            --depth=1 \
            --branch=main \
            https://github.com/armbian/build.git armbian.git
          ls -alh armbian.git
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile Armbian [ ${{ matrix.set_release }} ] [ ${{ matrix.set_desktop }} ]
        id: compile_armbian
        working-directory: /builder/armbian.git
        run: |
          if [ "${{ matrix.set_desktop }}" == "cli" ] ; then
            BUILD_DESKTOP="BUILD_DESKTOP=no"
          else
            BUILD_DESKTOP=" \
                BUILD_DESKTOP=yes \
                DESKTOP_APPGROUPS_SELECTED=remote_desktop \
                DESKTOP_ENVIRONMENT=${{ matrix.set_desktop }} \
                DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base"
          fi
          # BRANCH=edge    : newest kernel such as 6.10
          # BRANCH=current : stable kernel such as 6.6
          # BRANCH=legacy  : vendor kernel rockchip 5.10
          ./compile.sh RELEASE=${{ matrix.set_release }} \
                       BOARD=nanopct4 \
                       BRANCH=current \
                       BUILD_MINIMAL=no \
                       BUILD_ONLY=default \
                       HOST=armbian \
                       ${BUILD_DESKTOP} \
                       EXPERT=yes \
                       KERNEL_CONFIGURE=no \
                       COMPRESS_OUTPUTIMAGE="sha,img,xz" \
                       VENDOR="Armbian" \
                       SHARE_LOG=yes
          ls -alh /builder/armbian.git/output/images/
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: List Armbian
        working-directory: /builder/armbian.git/output/images/
        if: ${{ steps.compile_armbian.outputs.status }} == 'success' && !cancelled()
        run: |
          ls -alh /builder/armbian.git/output/images/

      - name: Upload Image to Release
        uses: ncipollo/release-action@main
        with:
          tag: Armbian_Image
          artifacts: /builder/armbian.git/output/images/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### Armbian_Image

            **For kdev, just for fun**
